### ISSUE TITLE
Color Scheme doesn't really fit well with our Company Logo and the green of the "Deep"

### ISSUE THREAD

**Issue by savas-guven** [deepnetworkgmbh/deepnetworkgmbh.github.io#1]
![image](https://user-images.githubusercontent.com/29249348/68670171-8b3e7100-054c-11ea-88ce-5e97724141e5.png)

**Comment by enesunal** [comment]
This is a big change, let's talk about it. Probably we need to switch the design`?`

**Comment by detaybey** [comment]
We should maybe;
- change orange with our green, 
- change the font
- a lighter blue instead of facebook blue
- get rid of white backgrounds

**Comment by yufufi** [comment]
That orange looks horrid 🤢

**Comment by detaybey** [comment]
This task would be much easier if we first do the cleanup (issue #37 - Get rid of unused JS/CSS resources)

**Comment by detaybey** [comment]
PR https://github.com/deepnetworkgmbh/deepnetworkgmbh.github.io/pull/48
