### ISSUE TITLE
Logo to be replaced with a higher resolution logo?

### ISSUE THREAD

**Issue by detaybey** [deepnetworkgmbh/deepnetworkgmbh.github.io#14]
Logo seems low quality, can be replaced with a high resolution one.

**Comment by detaybey** [comment]
can anyone provide raw materials for the logo?

**Comment by yufufi** [comment]
![DeepNetworkLogo](https://user-images.githubusercontent.com/1406759/69144160-f6e38980-0aca-11ea-9e0e-e925767577a9.jpg)

This is the biggest version I have. Savas might have something bigger. @deepnetwork

**Comment by savas-guven** [comment]
Mine is always bigger.
[DEEPNETWORK LOGO.pdf](https://github.com/deepnetworkgmbh/deepnetworkgmbh.github.io/files/3868464/DEEPNETWORK.LOGO.pdf)
![DEEPNETWORK LOGO](https://user-images.githubusercontent.com/29249348/69228034-2eae0800-0b83-11ea-88bb-05442251fab8.png)
![Uploading DEEPNETWORK LOGO.jpg…]()

**Comment by savas-guven** [comment]
![DEEPNETWORK LOGO](https://user-images.githubusercontent.com/29249348/69228235-8187bf80-0b83-11ea-9e6b-fba16c8e0237.png)
![DEEPNETWORK LOGO](https://user-images.githubusercontent.com/29249348/69228236-82205600-0b83-11ea-8f75-ad8abeb19429.jpg)
