### ISSUE TITLE
Remove the sidebar

### ISSUE THREAD

**Issue by detaybey** [deepnetworkgmbh/deepnetworkgmbh.github.io#16]
It can be removed, we don’t have a complicated navigation.

**Comment by enesunal** [comment]
It's there since we don't have room for all the items on mobile phones etc. What we can use instead of it? Or just don't show the sidebar on higher resolutions?

**Comment by detaybey** [comment]
well, i proposed it considering that we want our website done correctly.
we do not have a complicated navigation three. for our website this is overcomplicating things and looks amateur.

for mobile we must have a sticking navigation at top, and must be handled using css media features. but it's another design work.

even the pulldown must be removed from the menu, any additional click for user to reach a content must be eliminated.

**Comment by ghost** [comment]
resolved with `redesign-2021` branch
