### ISSUE TITLE
Remove left-right arrows on carousel

### ISSUE THREAD

**Issue by detaybey** [deepnetworkgmbh/deepnetworkgmbh.github.io#18]

**Comment by yufufi** [comment]
The only other way to navigate is to either wait or click on the dots down below which are both not easy. What's your suggestion here? Just remove them or put something else in place?

**Comment by detaybey** [comment]
user does not navigate from any content within the carousel. it is a filler-content. nobody will have the need of clicking those buttons because it is already auto animating every 3 seconds.

**Comment by enesunal** [comment]
It's really hard to navigate by using dots & by waiting. If we have an alternative for that; you're right we can remove them. Please reopen the issue if we have a better alternative.
