### ISSUE TITLE
Carousel has a glitch before page load

### ISSUE THREAD

**Issue by detaybey** [deepnetworkgmbh/deepnetworkgmbh.github.io#19]
it goes left for 20px then goes right after page load

**Comment by enesunal** [comment]
@detaybey I couldn't reproduce this. Which browser is it? And how long it stays there?

**Comment by detaybey** [comment]
![glitch](https://user-images.githubusercontent.com/784409/69717407-1018b580-111d-11ea-82ca-c74f7bad0881.gif)
like 2-3 seconds. happens on firefox, chrome, brave, looks like everything.

**Comment by detaybey** [comment]
PR https://github.com/deepnetworkgmbh/deepnetworkgmbh.github.io/pull/44
