### ISSUE TITLE
Create/Update the Job Openings with our current type of openings.

### ISSUE THREAD

**Issue by savas-guven** [deepnetworkgmbh/deepnetworkgmbh.github.io#2]

**Comment by enesunal** [comment]
Could you please provide more information on this one?

**Comment by savas-guven** [comment]
@yufufi -- can we put one of your Full Stack developer postings + a DevOps/BackEnd developer type position? 

and keep them up to date.

**Comment by ghost** [comment]
resolved with `redesign-2021` branch
