### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by detaybey** [deepnetworkgmbh/deepnetworkgmbh.github.io#20]

**Comment by yufufi** [comment]
@detaybey could you please be more specific with the issue?

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1406759/69162781-73875f80-0aed-11ea-9bf4-5d4dd03da197.png">

**Comment by detaybey** [comment]
Is this particularly for my connection? 

<img width="661" alt="Screen Shot 2019-11-20 at 12 50 10" src="https://user-images.githubusercontent.com/784409/69228341-6ffae380-0b94-11ea-82fb-4f14b71aeae4.png">

**Comment by savas-guven** [comment]
Can you click `More Information` and provide that data?

**Comment by detaybey** [comment]
Oh I think I got it. We seem to be not redirecting `http` requests to `https`
try accessing http://deepnetwork.com
Our SSL works fine, we just have no redirection.

**Comment by savas-guven** [comment]
Ah.. I'd be ok with no redirection at this point.

**Comment by enesunal** [comment]
Created #28 for that.
