### ISSUE TITLE
Map on contact us gives a load error.

### ISSUE THREAD

**Issue by detaybey** [deepnetworkgmbh/deepnetworkgmbh.github.io#21]

**Comment by yufufi** [comment]
I see the map just fone, @detaybey could you please provide more details.

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/1406759/69162570-286d4c80-0aed-11ea-86e8-6d1d99c36d82.png">

**Comment by enesunal** [comment]
Happens on Chrome version 78.0.3904.97

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/5593342/69227677-8730d580-0b82-11ea-9113-52520ec00e77.png">

**Comment by savas-guven** [comment]
Visually the Map is visible on my Chrome -- are you guys talking about something else?

**Comment by enesunal** [comment]
Yeap visually map is not visible at all on Chrome on macOS. Since @detaybey and I can reproduce it, we'll try to figure out I guess.

**Comment by yufufi** [comment]
Timing issue. map initialization script may run before google maps JS is ready. sending a quick and dirty fix
