### ISSUE TITLE
The site saves a cookie before the user gives consent

### ISSUE THREAD

**Issue by yufufi** [deepnetworkgmbh/deepnetworkgmbh.github.io#24]
<img width="1801" alt="image" src="https://user-images.githubusercontent.com/1406759/69144725-36f73c00-0acc-11ea-8629-8780f8291849.png">

**Comment by detaybey** [comment]
PR https://github.com/deepnetworkgmbh/deepnetworkgmbh.github.io/pull/43

**Comment by detaybey** [comment]
please check the PR
