### ISSUE TITLE
When menu items disappear on low width, there is no bottom marging/padding for the burger menu

### ISSUE THREAD

**Issue by yufufi** [deepnetworkgmbh/deepnetworkgmbh.github.io#31]
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/1406759/69242621-4badff80-0bb2-11ea-95dd-acfcb92f1ebc.png">

vs

![image](https://user-images.githubusercontent.com/1406759/69242677-684a3780-0bb2-11ea-8ded-be4cce057770.png)

**Comment by detaybey** [comment]
https://github.com/deepnetworkgmbh/deepnetworkgmbh.github.io/pull/34
