### ISSUE TITLE
Garbled UI Elements on Chrome/Windows on first load.

### ISSUE THREAD

**Issue by savas-guven** [deepnetworkgmbh/deepnetworkgmbh.github.io#35]
**Repro steps** 
- either ctrl-F5, or do a first time load of home page.
- Issue resolves after first slider action.

Expected Behavior:
- First time load acts normal.

Observe the following for few seconds:

![image](https://user-images.githubusercontent.com/29249348/69856559-31e57a00-128e-11ea-9df4-413e3820fc51.png)

After a while it fixes itself as following:
![image](https://user-images.githubusercontent.com/29249348/69856652-6822f980-128e-11ea-931b-9bafe90790e4.png)

**Comment by enesunal** [comment]
Duplicates #19 .
