### ISSUE TITLE
Misalignment on home page Windows/Chrome

### ISSUE THREAD

**Issue by savas-guven** [deepnetworkgmbh/deepnetworkgmbh.github.io#41]
There is alignment problems :
Windows / Chrome:

![image](https://user-images.githubusercontent.com/29249348/69877898-adade980-12c3-11ea-92b5-fa130cd84e81.png)

also visible here:
![image](https://user-images.githubusercontent.com/29249348/69877920-b8687e80-12c3-11ea-8a38-31d502d88cf1.png)

**Comment by enesunal** [comment]
Similar to #19

**Comment by detaybey** [comment]
I believe PR https://github.com/deepnetworkgmbh/deepnetworkgmbh.github.io/pull/44 also fixed this
