### ISSUE TITLE
Fix new arrow icons alignment

### ISSUE THREAD

**Issue by enesunal** [deepnetworkgmbh/deepnetworkgmbh.github.io#47]
Arrows should be centered in boxes, examples: 

<img width="817" alt="image" src="https://user-images.githubusercontent.com/5593342/70143896-0c48de00-169d-11ea-845f-ffe41048b1c6.png">

<img width="160" alt="image" src="https://user-images.githubusercontent.com/5593342/70143878-005d1c00-169d-11ea-801d-a758810cc63d.png">

**Comment by enesunal** [comment]
Arrows shouldn't be cut, example: 

<img width="494" alt="image" src="https://user-images.githubusercontent.com/5593342/70143940-2a164300-169d-11ea-972e-b73606622fc3.png">

**Comment by detaybey** [comment]
please check PR https://github.com/deepnetworkgmbh/deepnetworkgmbh.github.io/pull/57

**Comment by detaybey** [comment]
PR https://github.com/deepnetworkgmbh/deepnetworkgmbh.github.io/pull/57 merged, closing.
