### ISSUE TITLE
The map in the contact-us page is broken/not loading

### ISSUE THREAD

**Issue by yufufi** [deepnetworkgmbh/deepnetworkgmbh.github.io#50]
This seems to be introduced with #36

**Comment by detaybey** [comment]
please check PR https://github.com/deepnetworkgmbh/deepnetworkgmbh.github.io/pull/56

**Comment by detaybey** [comment]
PR https://github.com/deepnetworkgmbh/deepnetworkgmbh.github.io/pull/56 merged, closing.
