### ISSUE TITLE
Request a Demo page does not work

### ISSUE THREAD

**Issue by yufufi** [deepnetworkgmbh/deepnetworkgmbh.github.io#51]
https://www.deepnetwork.com/request-a-demo.html

* It's a dynamic form that posts to www.otomobilgi.com
* The captcha control doesn't work

This page is linked from https://www.deepnetwork.com/our-solutions.html page. In the bottom there is a "Request a demo" button that links to this page.

My suggestion is to convert this to an "mailto:" with some subject and content.

`Subject:`
Requesting PrimeApps Demo
`Content:`
Name:
Company:
E-Mail:
Phone Number:

@deepnetwork please comment.

**Comment by detaybey** [comment]
this is already done, there is a PR that waits your approval https://github.com/deepnetworkgmbh/deepnetworkgmbh.github.io/pull/45

**Comment by ghost** [comment]
this is no longer relevant with `redesign-2021` branch
