### ISSUE TITLE
We should use our own key for embedding google maps

### ISSUE THREAD

**Issue by yufufi** [deepnetworkgmbh/deepnetworkgmbh.github.io#58]
I think we're using the one that the developer created (and is very likely sharing across his other projects) I've hit usage limits just now and given the traffic on our site this is very weird.

![image](https://user-images.githubusercontent.com/1406759/71716961-bdff3a00-2e16-11ea-9a2a-dd6bb4250c1f.png)

@deepnetwork can you follow the steps in [here](https://developers.google.com/maps/documentation/embed/get-api-key) to get us a new key please?

**Comment by ghost** [comment]
no longer relevant with `redesign-2021` branch
