### ISSUE TITLE
Learn More buttons do not do anything

### ISSUE THREAD

**Issue by yufufi** [deepnetworkgmbh/deepnetworkgmbh.github.io#59]
![image](https://user-images.githubusercontent.com/1406759/71719557-0a4e7800-2e1f-11ea-9491-6dee20bc8359.png)

**Comment by yufufi** [comment]
It doesn't work on the [original](http://www.otomobilgi.com/deepnetwork/) either.

**Comment by ghost** [comment]
resolved with `redesign-2021` branch
