### ISSUE TITLE
Disable/change "Request a Demo" page

### ISSUE THREAD

**Issue by enesunal** [deepnetworkgmbh/deepnetworkgmbh.github.io#9]
It's not working since it's interactive. We can map this link to `mailto:info@deepnetwork.com?subject=I need a Demo` or something alike.

**Comment by enesunal** [comment]
What do you think? @deepnetwork @yufufi ?

**Comment by savas-guven** [comment]
Should send an e-mail to info@deepnetwork.com with a subject of "REQUEST A DEMO" maybe?

**Comment by detaybey** [comment]
please check PR https://github.com/deepnetworkgmbh/deepnetworkgmbh.github.io/pull/45

**Comment by detaybey** [comment]
PR #45 is approved and merged.
